[meta]
name  = "投资组合"
start = "2025-01-02"
end   = "2025-12-31"

[portfolio]
total_capital = 1_000_000

[assets.510300]
name    = "沪深300ETF"
weight  = 0.25
is_cash = false

[assets.518880]
name    = "黄金ETF"
weight  = 0.25
is_cash = false

[assets.511620]
name      = "货币ETF"
weight    = 0.25
is_cash   = true
cash_rate = 0.015

[assets.511090]
name    = "30年国债ETF"
weight  = 0.25
is_cash = false

[strategy]
type = "threshold_and_periodic"

[strategy.params]
drift           = 0.05
periodic_months = [3, 6, 9, 12]
